# Generated by Django 5.0.7 on 2024-08-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('scheduled', 'scheduled'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=50),
        ),
    ]
