# Generated by Django 5.0.7 on 2024-08-03 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_medicalrecord_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_status', to='patient.appointment'),
        ),
    ]
